name: SaintsyFly
main: iiSaints83\SaintsyFly\SaintsyFly
description: An advanced survival fly plugin!
version: 1.8.7
api: 3.0.0
author: iiFlamiinBlaze
commands:
  fly:
    description: "Command which allows flight when in Survival Mode!"
permissions:
  blazinfly.command:
    description: "BlazinFly command permission"
    default: op
  blazinfly.other:
    description: "Allow you to activate fly for other players"
    default: op
